package cs2340.spacetraders.entity;

public enum CelestialName {
     Acamar("Acamar"),
     Adahn ("Adahn"),
     Aldea  ("Aldea"),
     Andevian  ("Andevian"),
     Antedi  ("Antedi"),
     Balosnee  ("Balosnee"),
     Baratas  ("Baratas"),
     Brax  ("Brax"),
     Bretel  ("Bretel"),
     Calondia  ("Calondia"),
     Campor  ("Campor"),
     Capelle  ("Capelle"),
     Carzon  ("Carzon"),
     Castor  ("Castor"),
     Cestus  ("Cestus"),
     Cheron  ("Cheron"),
     Courteney  ("Courteney"),
     Daled  ("Daled"),
     Damast  ("Damast"),
     Davlos  ("Davlos"),
     Deneb  ("Deneb"),
     Deneva  ("Deneva"),
     Devidia  ("Devidia"),
     Draylon  ("Draylon"),
     Drema  ("Drema"),
     Endor  ("Endor"),
     Esmee  ("Esmee"),
     Exo  ("Exo"),
     Ferris  ("Ferris"),
     Festen  ("Festen"),
     Fourmi  ("Fourmi"),
     Frolix ("Frolix"),
     Gemulon ("Gemulon"),
     Guinifer ("Guinifer"),
     Hades ("Hades"),
     Hamlet ("Hamlet"),
     Helena ("Helena"),
     Hulst ("Hulst"),
     Iodine ("Iodine"),
     Iralius ("Iralius"),
     Janus ("Janus"),
     Japori ("Japori"),
     Jarada ("Jarada"),
     Jason ("Jason"),
     Kaylon ("Kaylon"),
     Khefka ("Khefka"),
     Kira ("Kira"),
     Klaatu ("Klaatu"),
     Klaestron ("Klaestron"),
     Korma ("Korma"),
     Kravat ("Kravat"),
     Krios ("Krios"),
     Laertes (""),
     Largo (""),
     Lave (""),
     Ligon (""),
     Lowry (""),
     Magrat (""),
     Malcoria (""),
     Melina (""),
     Mentar (""),
     Merik (""),
     Mintaka (""),
     Montor (""),
     Mordan (""),
     Myrthe (""),
     Nelvana (""),
     Nix (""),
     Nyle (""),
     Odet (""),
     Og (""),
     Omega (""),
     Omphalos (""),
     Orias (""),
     Othello (""),
     Parade (""),
     Penthara (""),
     Picard (""),
     Pollux (""),
     Quator (""),
     Rakhar (""),
     Ran (""),
     Regulas (""),
     Relva (""),
     Rhymus (""),
     Rochani (""),
     Rubicum (""),
     Rutia (""),
     Sarpeidon (""),
     Sefalla (""),
     Seltrice (""),
     Sigma (""),
     Sol (""),
     Somari (""),
     Stakoron (""),
     Styris (""),
     Talani (""),
     Tamus (""),
     Tantalos (""),
     Tanuga (""),
     Tarchannen (""),
     Terosa (""),
     Thera (""),
     Titan (""),
     Torin (""),
     Triacus (""),
     Turkana (""),
     Tyrus (""),
     Umberlee (""),
     Utopia (""),
     Vadera (""),
     Vagra (""),
     Vandor (""),
     Ventax (""),
     Xenon (""),
     Xerxes (""),
     Yew (""),
     Yojimbo (""),
     Zalkon (""),
     Zuul("");

    private final String name;
     
     CelestialName(String name) {
         this.name = name;
     }


    public String getName() {
        return name;
    }
}
