package cs2340.spacetraders.entity.Universe;

/**
 * Enum for possible names for planets and other celestial bodies
 */
public enum CelestialName {
     Acamar("Acamar"),
     Adahn ("Adahn"),
     Aldea  ("Aldea"),
     Andevian  ("Andevian"),
     Antedi  ("Antedi"),
     Balosnee  ("Balosnee"),
     Baratas  ("Baratas"),
     Brax  ("Brax"),
     Bretel  ("Bretel"),
     Calondia  ("Calondia"),
     Campor  ("Campor"),
     Capelle  ("Capelle"),
     Carzon  ("Carzon"),
     Castor  ("Castor"),
     Cestus  ("Cestus"),
     Cheron  ("Cheron"),
     Courteney  ("Courteney"),
     Daled  ("Daled"),
     Damast  ("Damast"),
     Davlos  ("Davlos"),
     Deneb  ("Deneb"),
     Deneva  ("Deneva"),
     Devidia  ("Devidia"),
     Draylon  ("Draylon"),
     Drema  ("Drema"),
     Endor  ("Endor"),
     Esmee  ("Esmee"),
     Exo  ("Exo"),
     Ferris  ("Ferris"),
     Festen  ("Festen"),
     Fourmi  ("Fourmi"),
     Frolix ("Frolix"),
     Gemulon ("Gemulon"),
     Guinifer ("Guinifer"),
     Hades ("Hades"),
     Hamlet ("Hamlet"),
     Helena ("Helena"),
     Hulst ("Hulst"),
     Iodine ("Iodine"),
     Iralius ("Iralius"),
     Janus ("Janus"),
     Japori ("Japori"),
     Jarada ("Jarada"),
     Jason ("Jason"),
     Kaylon ("Kaylon"),
     Khefka ("Khefka"),
     Kira ("Kira"),
     Klaatu ("Klaatu"),
     Klaestron ("Klaestron"),
     Korma ("Korma"),
     Kravat ("Kravat"),
     Krios ("Krios"),
     Laertes ("Laertes"),
     Largo ("Largo"),
     Lave ("Lave"),
     Ligon ("Ligon"),
     Lowry ("Lowry"),
     Magrat ("Magrat"),
     Malcoria ("Malcoria"),
     Melina ("Melina"),
     Mentar ("Mentar"),
     Merik ("Merik"),
     Mintaka ("Mintaka"),
     Montor ("Montor"),
     Mordan ("Mordan"),
     Myrthe ("Myrthe"),
     Nelvana ("Nelvana"),
     Nix ("Nix"),
     Nyle ("Nyle"),
     Odet ("Odet"),
     Og ("Og"),
     Omega ("Omega"),
     Omphalos ("Omphalos"),
     Orias ("Orias"),
     Othello ("Othello"),
     Parade ("Parade"),
     Penthara ("Penthara"),
     Picard ("Picard"),
     Pollux ("Pollux"),
     Quator ("Quator"),
     Rakhar ("Rakhar"),
     Ran ("Ran"),
     Regulas ("Regulas"),
     Relva ("Relva"),
     Rhymus ("Rhymus"),
     Rochani ("Rochani"),
     Rubicum ("Rubicum"),
     Rutia ("Rutia"),
     Sarpeidon ("Sarpeidon"),
     Sefalla ("Sefalla"),
     Seltrice ("Seltrice"),
     Sigma ("Sigma"),
     Sol ("Sol"),
     Somari ("Somari"),
     Stakoron ("Stakoron"),
     Styris ("Styris"),
     Talani ("Talani"),
     Tamus ("Tamus"),
     Tantalos ("Tantalos"),
     Tanuga ("Tanuga"),
     Tarchannen ("Tarchannen"),
     Terosa ("Terosa"),
     Thera ("Thera"),
     Titan ("Titan"),
     Torin ("Torin"),
     Triacus ("Triacus"),
     Turkana ("Turkana"),
     Tyrus ("Tyrus"),
     Umberlee ("Umberlee"),
     Utopia ("Utopia"),
     Vadera ("Vadera"),
     Vagra ("Vagra"),
     Vandor ("Vandor"),
     Ventax ("Ventax"),
     Xenon ("Xenon"),
     Xerxes ("Xerxes"),
     Yew ("Yew"),
     Yojimbo ("Yojimbo"),
     Zalkon ("Zalkon"),
     Zuul("Zuul");

    private final String name;
     
     CelestialName(String name) {
         this.name = name;
     }

    /**
     * Returns the name of the celestial body
     * @return name
     */
    public String getName() {
        return name;
    }
}
